/* GENERATED by scripts/ingest-photos.py — do not hand-edit.
   Photographs of the team, cropped out of the supplied screenshots.
   Regenerate by dropping files in incoming/photos/roboticsteam and
   re-running the script; the list always matches what is on disk. */
export type OutreachPhoto = { src: string; caption?: string };

export const outreachPhotos: OutreachPhoto[] = [
  { src: '/assets/outreach/outreach-26.jpg' },
  { src: '/assets/outreach/outreach-01.jpg' },
  { src: '/assets/outreach/outreach-27.jpg' },
  { src: '/assets/outreach/outreach-19.jpg' },
  { src: '/assets/outreach/outreach-13.jpg' },
  { src: '/assets/outreach/outreach-11.jpg' },
  { src: '/assets/outreach/outreach-21.jpg' },
  { src: '/assets/outreach/outreach-12.jpg' },
  { src: '/assets/outreach/outreach-14.jpg' },
  { src: '/assets/outreach/outreach-16.jpg' },
  { src: '/assets/outreach/outreach-07.jpg' },
  { src: '/assets/outreach/outreach-06.jpg' },
  { src: '/assets/outreach/outreach-05.jpg' },
  { src: '/assets/outreach/outreach-08.jpg' },
  { src: '/assets/outreach/outreach-24.jpg' },
  { src: '/assets/outreach/outreach-10.jpg' },
  { src: '/assets/outreach/outreach-25.jpg' },
  { src: '/assets/outreach/outreach-17.jpg' },
  { src: '/assets/outreach/outreach-15.jpg' },
  { src: '/assets/outreach/outreach-22.jpg' },
  { src: '/assets/outreach/outreach-04.jpg' },
  { src: '/assets/outreach/outreach-18.jpg' },
  { src: '/assets/outreach/outreach-23.jpg' },
  { src: '/assets/outreach/outreach-03.jpg' },
  { src: '/assets/outreach/outreach-20.jpg' },
  { src: '/assets/outreach/outreach-02.jpg' },
  { src: '/assets/outreach/outreach-09.jpg' },
];
